### ISSUE TITLE
Support for Seeed Wio Terminal

### ISSUE THREAD

**Issue by windoze** [platformio/platform-atmelsam#107]
Can you add support for Seeed Wio Terminal?

**[Seeed Wio Terminal (ATSAMD51P19)](https://www.seeedstudio.com/Wio-Terminal-p-4509.html)**.

Thanks a lot!

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-atmelsam/commit/0ed89cea0a96ce960279e34c9f4fb763e728fbcd .You can try it in the upstream version of the platform https://docs.platformio.org/en/latest/platforms/atmelsam.html#stable-and-upstream-versions
