### ISSUE TITLE
Configuration of ATMEL-ICE

### ISSUE THREAD

**Issue by dpeinado** [platformio/platform-atmelsam#109]
Hello, I'm using Arduino Due with Atmel-Ice for debugging.
As found in other discussion: https://community.platformio.org/t/help-with-pio-debugger-using-atmel-ice-and-arduino-due/8759/34

I needed to put in my platformio.init
debug_server = 
    /home/user/.platformio/packages/tool-openocd/bin/openocd -d2 -s
    /home/user/.platformio/packages/tool-openocd/scripts -f interface/cmsis-dap.cfg
	-c "set CHIPNAME at91sam3X8E"
	-c  "source [find target/at91sam3ax_8x.cfg

This is independent of the IDE used. I have to include this code using VS and using CLion.
It should be done by default. Thanks.

**Comment by valeros** [comment]
Hi @dpeinado ! Thanks for the report. Could you please delete your custom `debug_server` option and try the upstream version of the platform:
```
[env:due]
platform = https://github.com/platformio/platform-atmelsam.git
framework = arduino
board = due
debug_tool = atmel-ice
```
Thanks!
