### ISSUE TITLE
No load on Arduino MkrZero

### ISSUE THREAD

**Issue by PLambertk** [platformio/platform-atmelsam#11]
Unable to load the basic Blink program to an Arduino MkrZero, Compile completes OK, then  I get the following messages :

Looking for upload port…
Auto-detected: COM6
Forcing reset using 1200bps open/close on port COM6
Uploading .pioenvs\mkrzero\firmware.bin
Atmel SMART device 0x100110005 found
SAM-BA operation failed
*** [upload] error 1
[ERROR] took 46.3 seconds

**Comment by ivankravets** [comment]
Please re-test current development branch:

* Uninstall existing development platform `pio platform uninstall atmelsam`
* Install development version `pio platform install https://github.com/platformio/platform-atmelsam.git`

**Comment by PLambertk** [comment]
Thank you Ivan for taking the time to address the issue.
My project being rather urgent I have switched to a different IDE since I reported the issue. However I will get back to platformio when I'm done and will report my test results then.

**Comment by ivankravets** [comment]
Would be thankful if you help us to resolve this issue!

**Comment by ivankravets** [comment]
If someone experience this issue, please provide more details

**Comment by ivankravets** [comment]
Please reopen if you still need help
