### ISSUE TITLE
Please add support for SeeedStudio XIAO

### ISSUE THREAD

**Issue by windoze** [platformio/platform-atmelsam#117]
What kind of issue is this?

- [x] **Feature Request**.
      Please add support for [Seeeduino XIAO](https://www.seeedstudio.com/Seeeduino-XIAO-Arduino-Microcontroller-SAMD21-Cortex-M0+-p-4426.html)
      It uses SAMD21G18, which is same as (or similar to) Adafruit Circuit Playground Express.

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platform-atmelsam/issues/102
