### ISSUE TITLE
SAMR34 , Platform IO Hex/bin/elf does not work with custom board

### ISSUE THREAD

**Issue by Krunal090** [platformio/platform-atmelsam#131]
Hello Everyone ,
I am new for Platform IO.
I have SAMR34 Xplained Pro Evaluation Kit and program run perfect with inbuilt EDBG chip with platform IO with Visual code studio.
Now i will load same hex in custom board with j-link EDU from atmel studio then SAMR34 not initiated . But if I make sample code in ATMEL studio then hardware run perfect.
So let me know the solution which i have made in SAMR34 Xplained Pro Evaluation Kit and how can i load that hex file in Custom developed board to make it run.

**Comment by Krunal090** [comment]
Does any one make firmware with platform IO and load this hex to making custom board ?

**Comment by valeros** [comment]
Hi @Krunal090 ! What framework do you use with your `SAMR34 Xplained Pro Evaluation Kit`?

**Comment by Krunal090** [comment]
@valeros , used below platform.
https://github.com/Wiz-IO/platform-sam-lora

**Comment by valeros** [comment]
Please open an issue in that repository.
