### ISSUE TITLE
[Question] Programm MCU directly

### ISSUE THREAD

**Issue by Gurkengewuerz** [platformio/platform-atmelsam#138]
First of all I hope you had a nice Christmas!

i want to do my first steps using the SAMD21-series. For my upcoming project i want to programm a ATSAMD21E17A directly but I do not yet understand the settings correctly. Somehow you can specify the mcu but you also need a board specification???

Is programming a sam device directly using a atmel ice supported? Do i have to write my own board.json or just the correct platformio.ini entry?
Maybe @valeros can help here? 🙈

Thanks in advanced and greetings from Germany!
\- Niklas

**Comment by valeros** [comment]
Hi Niklas,

What framework do you plan to use? If I'm not mistaken, none of the frameworks in this repository supports `ATSAMD21E17A` precisely.  In your case, you will need to write a custom board manifest where you specify proper debug options like `jlink_device` and `openocd_chipname` so you will be able to upload apps using `atmel-ice`.

PS: This repository is not the right place to ask such questions, next time please open a topic here https://community.platformio.org/
