### ISSUE TITLE
Update framework-arduino-samd-seeed to fix critical errors for Xiao Seeed board

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-atmelsam#146]
Per https://community.platformio.org/t/updating-support-for-seed-xiao/19135/ the I2C on that board doesn't work in the core version 1.7.3 that the platform is currently using, but starting from 1.8.0 it's fixed (current version is 1.8.1).

I'd suggest to publish an updated `framework-arduino-samd-seeed` package and use it in the `platform.json` of this platform.

A current workaround is doing

```
[env:seeed_xiao]
platform = atmelsam
board = seeed_xiao
framework = arduino
; update to latest git version
platform_packages = 
    framework-arduino-samd-seeed@https://github.com/Seeed-Studio/ArduinoCore-samd.git#v1.8.1
```
which successfully builds the firmware with the newer core version.

**Comment by david3a** [comment]
This will also make the on board blue leds work as well, either a rx/tx slaves or as pins if needed
