### ISSUE TITLE
Version 6.0.0 does not compile for Seeed XIAO with SPI

### ISSUE THREAD

**Issue by savejeff** [platformio/platform-atmelsam#149]
Yesterday I updated to the 6.0.0 version on PlatformIO
Using SPI gives me a compile error: 
![image](https://user-images.githubusercontent.com/11009455/109625957-3909d080-7b40-11eb-88fa-31552d198fa0.png)

using this simple code:
```
#include <Arduino.h>
#include "SPI.h"
void setup() {
  SPI.begin();  
}
void loop() { 
}

```

platformio.ini: 
```

[env:seeed_xiao]
platform = atmelsam
board = seeed_xiao
framework = arduino

```

**Comment by valeros** [comment]
Thanks for reporting. Should be fixed in the development branch, please try to compile your project using the following configurtion:
```
[env:seeed_xiao]
platform = https://github.com/platformio/platform-atmelsam.git
board = seeed_xiao
framework = arduino
```

**Comment by savejeff** [comment]
Oh i didn't knwo you could just use the github link to the platform code. Nice to know. 

For now, I will just downgrade to 5.1.1 in PlatformIO and wait for a new version
