### ISSUE TITLE
Update SodaqCore-samd to version 1.8.6

### ISSUE THREAD

**Issue by matthias-mueller** [platformio/platform-atmelsam#156]
It currently sits at `1.6.20` which is severely outdated.

The current stable SodaqCore-samd version is `1.8.6`:

https://forum.sodaq.com/t/sodaqcore-samd-v1-8-6/3342

Although there has been some discussion/work in #93 it seems that no upgrade actually happened.

**Comment by maxgerhardt** [comment]
+1 to this -- the branching / tag structure on the https://github.com/SodaqMoja/SodaqCore-samd/ core is also pretty damn confusing in the SODAQ core. The default branch points to 1.6.15. There are no releases on the github, only tags.

**Comment by matthias-mueller** [comment]
Thanks for handling this @valeros !

**Comment by valeros** [comment]
@matthias-mueller Please retest with the upstream version:
```ini
[env:sodaq_explorer]
platform = https://github.com/platformio/platform-atmelsam.git
framework = arduino
board = sodaq_explorer
```

**Comment by matthias-mueller** [comment]
@valeros Sorry to disappint you - but I'm just a "standard" user of PlatformIO and use the version that's visible to the VSCode plugin system.

**Comment by matthias-mueller** [comment]
@valeros Compilation works a first tests look okay:

```ini
[env:sodaq_sff]
platform = https://github.com/platformio/platform-atmelsam.git
board = sodaq_sff
framework = arduino
```

**Comment by keestux** [comment]
Thanks for the update
