### ISSUE TITLE
**Feature Request** - Addition of Macchina M2 to boards please :)

### ISSUE THREAD

**Issue by joehodgy** [platformio/platform-atmelsam#162]
Pretty please with bells on :)

Thanks

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platform-atmelsam/issues/127

**Comment by joehodgy** [comment]
The linked thread in question does not offer a solution.

**Comment by joehodgy** [comment]
> Duplicate #127

Valeros the solution described does not work with current PIO build.

Please reopen the request.

Thanks

**Comment by valeros** [comment]
#127 is already describes your request, there is no need to duplicate them.
