### ISSUE TITLE
bossa source code?

### ISSUE THREAD

**Issue by guerby** [platformio/platform-atmelsam#17]
Hi,

tool-bossa package.json says:
```json
    "description": "Basic Open Source SAM-BA Application (BOSSA)",
    "name": "tool-bossac",
    "system": "linux_x86_64",
    "url": "https://github.com/shumatech/BOSSA",
    "version": "1.10700.0"
```

I cannot find in the shumatech/BOSSA reference to "1.10700.0" (no result via google except platformio :) ), where can I find the source code and build options used to produce the bossac binary (URL below) provided by tool-bossac?

https://bintray.com/platformio/dl-packages/tool-bossac#files

Thanks!

**Comment by ivankravets** [comment]
"1.10700.0" - this is an internal version of PIO Package Manager. The MINOR version is s real version of a package. In this case, it's 1.7.0. See:

https://github.com/shumatech/BOSSA/releases
