### ISSUE TITLE
Add -u to avrdude for arduino.org M0

### ISSUE THREAD

**Issue by lights0123** [platformio/platform-atmelsam#20]
I've been trying recently to use a (clone) arduino.org M0, which avrdude has had a hard time uploading to, at least outside of the IDE. This isn't just my problem, as a forum post at http://www.arduino.org/forums/zero?p=5683 mentioned it, but nothing I've found has an archive of it, and I only found it because of DuckDuckGo's cached search results. I played around with it, and it appears that avrdude in the Arduino IDE doesn't read the fuses, but it does outside of the IDE. For PlatformIO to successfully upload to the M0, the -u argument needs to be added to avrdude. I'm running PlatformIO 3.4.1 on MacOS 10.12.4.

**Comment by ivankravets** [comment]
Thanks a lot for the report!
