### ISSUE TITLE
PlatformIO uses framework-arduino-samd-seeed version 1.8.4 by default

### ISSUE THREAD

**Issue by Kita-Neko** [platformio/platform-atmelsam#220]
PlatformIO uses framework-arduino-samd-seeed version 1.8.4 which causes issues with TinyUSB. More context available here: `https://community.platformio.org/t/platfotmio-cannot-find-tinyusb/37307/6`

**Comment by stripwax** [comment]
It appears that this has been fixed at some point and can be closed.  The default version seems to be 1.8.5 .
