### ISSUE TITLE
Use ELF file for OpenOCD uploads, not bin

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-atmelsam#233]
When setting up an Arduino Due with `upload_protocol = stlink`, the upload by-default **fails** because the upload is trying to use the `.bin` file without giving the correct start address of flash `0x80000`, so OpenOCD assumes `0x0` and fails to find flash memory there.
 
See community post:

https://community.platformio.org/t/step-by-step-description-for-st-link-debugging-with-arduino-due/41624/3?u=maxgerhardt

Failing `platformio.ini`
```ini
[env:due]
platform = atmelsam
board = due
framework = arduino
debug_tool = stlink
upload_protocol = stlink
```

Upload failure

![140031dce5e50d9621b6326cd74d4adf8b756120](https://github.com/user-attachments/assets/73c1a14c-3715-4565-aa21-7158d8a8732f)

Fixed by manually adding (which shouldn't be needed)
```ini
board_upload.offset_address = 0x80000
```

**Comment by valeros** [comment]
Thanks for reporting, should be fixed in the dev branch.
