### ISSUE TITLE
Support for Adafruit ATSAMD51 M4 Series Boards

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-atmelsam#32]
These new ATSAMD51 M4 boards are likely to be very popular:

https://www.adafruit.com/product/3382

https://www.adafruit.com/product/3800

I have one of the latter on order, happy to test.

**Comment by ivankravets** [comment]
Please re-test with http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream

**Comment by blackketter** [comment]
Awesome, blink works great on adafruit_itsybitsy_m4!
