### ISSUE TITLE
Add board: SODAQ SARA N211

### ISSUE THREAD

**Issue by alessandroiori** [platformio/platform-atmelsam#34]
Hi,

Is it possible add [SODAQ SARA N211](http://support.sodaq.com/sodaq-one/sara/) board on PlatformIO?

The board is similar to SODAQ EXPLORER: [https://github.com/platformio/platform-atmelsam/blob/develop/boards/sodaq_explorer.json](https://github.com/platformio/platform-atmelsam/blob/develop/boards/sodaq_explorer.json)

AI

**Comment by alessandroiori** [comment]
Hello 👋 someone who can help me?

AI

**Comment by ivankravets** [comment]
Please re-test with upstream version. Does it work for you?
- http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
