### ISSUE TITLE
Add board request: Sodaq SARA 

### ISSUE THREAD

**Issue by Midnight28** [platformio/platform-atmelsam#35]
Hello!
I would like to ask you to add the Sodaq SARA board, link:

https://support.sodaq.com/sodaq-one/sodaq-sara-r410m/

Your work is appreciated a lot, thank you very much!

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-atmelsam/issues/34

**Comment by ivankravets** [comment]
Please re-test with upstream version. Does it work for you?
- http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
