### ISSUE TITLE
SAME5X patch for openocd

### ISSUE THREAD

**Issue by Timvrakas** [platformio/platform-atmelsam#43]
Boards based on SAMD51, SAME51, SAME54, etc. need OpenOCD with this patch
http://openocd.zylin.com/#/c/4272/
in order for `atmel-ice` uploading and debugging to work.
I just compiled and it all works as expected.

**Comment by ivankravets** [comment]
I see that the patch was merged into the upstream branch. Currently, we use openOCD binaries for ARM provided by @ilg-ul in https://github.com/gnu-mcu-eclipse/openocd

We can wait when Liviu release next binaries where this patch is included or you can file a feature request in this repository https://github.com/gnu-mcu-eclipse/openocd/issues

**Comment by Timvrakas** [comment]
Oh man, what are the chances of that timing? I didn't see that it was merged. I'll bring it up there.

**Comment by ilg-ul** [comment]
Could you test v0.10.0-12 from https://github.com/gnu-mcu-eclipse/openocd/releases ?

**Comment by ivankravets** [comment]
Please re-test with upstream version http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream

**Comment by coolio986** [comment]
I have just tried the upstream version for the SAMD51 on windows 10. Still the same issue, no uploading or debugging working. 

> Error: error during select: Unknown error
> .pioinit:12: Error in sourced command file:
> Remote communication error.  Target disconnected.: No error

.

**Comment by ivankravets** [comment]
Could you provide more details? What is your debug tool/adapter?

**Comment by coolio986** [comment]
I made a duplicate issue here:
[(https://github.com/platformio/platform-atmelsam/issues/59)]

Using an atmel-ice

> [env:adafruit_metro_m4]
> platform = atmelsam
> board = adafruit_metro_m4
> framework = arduino
> 
> debug_tool = atmel-ice
> upload_protocol = atmel-ice

**Comment by coolio986** [comment]
j-link works as expected, just not the ice

**Comment by ivankravets** [comment]
Let's move to this issue https://github.com/platformio/platform-atmelsam/issues/59
