### ISSUE TITLE
Feature Request: Add board Adafruit Grand Central

### ISSUE THREAD

**Issue by w3** [platformio/platform-atmelsam#46]
What kind of issue is this?

- [X] **Feature Request**.

### Additional info
Please add new board:
Adafruit Grand Central
Based on Atmel ATSAMD51P20A
Released Jan 2019.

**Comment by ivankravets** [comment]
Done! Please update dev/platform. See https://github.com/platformio/platform-atmelsam/blob/develop/boards/adafruit_grandcentral_m4.json
