### ISSUE TITLE
Feature Request: Adafruit PyPortal Board Support

### ISSUE THREAD

**Issue by daniel-stewart** [platformio/platform-atmelsam#55]
- [ ] **Feature Request**.
      I'd like to be able to use PlatformIO to program the Adafruit PyPortal (SAMD M4) in Arduino. I see there is support for other Adafruit boards, but not the PyPortal.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-atmelsam/issues/53

**Comment by ivankravets** [comment]
@daniel-stewart Please re-test with upstream version http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
