### ISSUE TITLE
Compiling a C++ sketch for Arduino DUE gives syntax errors

### ISSUE THREAD

**Issue by LorenzoDeMarco** [platformio/platform-atmelsam#62]
I tried to compile a previously working Arduino DUE sketch with the latest 'atmelsam' updates from PlatformIO (latest version).. but syntax errors pop out when compiling, all regarding `#define Max(a,b) (((a) > (b)) ? (a) : (b))` from the library source files: `Expected unqualified-id before '(' token`
The macro itself is correct, and I also found out that removing any occurrence of `std::map` in my code removes the errors... is there a solution for this issue?
Thanks in advance
Lorenzo
![image](https://user-images.githubusercontent.com/33262919/60274435-5496ef80-98f8-11e9-8c2c-0f05022c1302.png)

**Comment by valeros** [comment]
Does it work with the previous version of the platform?

**Comment by LorenzoDeMarco** [comment]
No, It doesn't. Attempting to use std::map causes the above messages to appear.
I tried to wrap all std::map members in conditional precompiler blocks as a test, and it seems that removing the std::maps from the code this way allows me to compile the sketch with no errors...

**Comment by valeros** [comment]
Hmm, I couldn't reproduce the issue. Could you put together a minimal example?

**Comment by ivankravets** [comment]
Please reopen if you still need help
