### ISSUE TITLE
Sparkfun Pro RF Support

### ISSUE THREAD

**Issue by MichaelFay** [platformio/platform-atmelsam#76]
Sparkfun released a lora equiped module with samd21. Can this board be added? 

https://www.sparkfun.com/products/14916?_ga=2.23413177.284850987.1567174339-1288849001.1567174339

**Comment by valeros** [comment]
Resolved in afd391496d7125237768f6f00f86fbc5098079ca. Please re-test with upstream version http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
