### ISSUE TITLE
Incorrect microcontroller defined for Adafruit monster m4sk 

### ISSUE THREAD

**Issue by doctorbigtime** [platformio/platform-atmelsam#83]
The platformio documentation and json defines incorrectly identify the adafruit monster m4sk's microcontroller as an SAMD51J19A when it is in fact an SAMD51G19 leading to build failures in libraries like the Adafruit ZeroTimer library.
Changing the `adafruit_monster_m4sk.json` to use the define -D__SAMD51G19A__ instead of -D__SAMD51J19A__ fixes this for me.

**Comment by valeros** [comment]
Thanks! Resolved in abbfb1b6ca74c27e8ca6e47e9132a4c31c883d05. Please re-test with upstream version http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
