### ISSUE TITLE
Please add board support for the SparkFun Qwiic Micro

### ISSUE THREAD

**Issue by spinoza1791** [platformio/platform-atmelsam#95]
Request to add PlatformIO board support for https://www.sparkfun.com/products/15423

https://github.com/sparkfun/SparkFun_Qwiic_Micro_SAMD21E

Thank you

**Comment by valeros** [comment]
Resolved in afd391496d7125237768f6f00f86fbc5098079ca. Please re-test with upstream version http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
